const products=[
{id:1,cat:'Płytki',brand:'CODICER',name:'Dice Grey 25×22 G.1',ean:'8435330131483',price:79.90,box:1.04,stock:0,img:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80'},
{id:2,cat:'Płytki',brand:'PARADYŻ',name:'Gres Stone Beige 60×60',ean:'5900000000002',price:94.90,box:1.44,stock:48,img:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80'},
{id:3,cat:'Płytki',brand:'TUBĄDZIN',name:'Monolith Grey 59,8×59,8',ean:'5900000000003',price:119.00,box:1.43,stock:32,img:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80'},
{id:4,cat:'Armatura',brand:'DEANTE',name:'Bateria umywalkowa chrom',ean:'5900000000004',price:329.00,box:null,stock:12,img:'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80'},
{id:5,cat:'Łazienka',brand:'ROCA',name:'Umywalka nablatowa 50 cm',ean:'5900000000005',price:489.00,box:null,stock:8,img:'https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=900&q=80'},
{id:6,cat:'Płytki',brand:'CERRAD',name:'Gres Modern Concrete 60×120',ean:'5900000000006',price:139.90,box:1.44,stock:65,img:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=900&q=80'}];
let category='Wszystkie',cart=[];
document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;render();document.querySelector('#products').scrollIntoView()});
function money(n){return n.toLocaleString('pl-PL',{style:'currency',currency:'PLN'})}
function render(){let q=document.querySelector('#search').value.toLowerCase().trim();let a=products.filter(p=>(category==='Wszystkie'||p.cat===category)&&(!q||`${p.name} ${p.brand} ${p.ean}`.toLowerCase().includes(q)));let s=document.querySelector('#sort').value;if(s==='priceAsc')a.sort((x,y)=>x.price-y.price);if(s==='priceDesc')a.sort((x,y)=>y.price-x.price);document.querySelector('#productGrid').innerHTML=a.map(p=>`<article class="product"><div class="product-img" style="background-image:url('${p.img}')"><span class="badge">${p.stock>0?'DOSTĘPNY':'NA ZAMÓWIENIE'}</span></div><div class="product-body"><span class="brand">${p.brand} · ${p.cat}</span><h3>${p.name}</h3><div class="meta">EAN: ${p.ean}${p.box?`<br>Pełna paczka: ${p.box} m²`:''}</div><div class="price">${money(p.price)} <small>${p.box?' / m²':' / szt.'}</small></div><div class="product-actions"><button onclick="details(${p.id})">Szczegóły</button><button class="buy" onclick="add(${p.id})">Do koszyka</button></div></div></article>`).join('')||'<p>Brak produktów spełniających kryteria.</p>'}
function add(id){let p=products.find(x=>x.id===id);cart.push(p);updateCart();if(!document.querySelector('#cartPanel').classList.contains('open'))toggleCart()}
function updateCart(){document.querySelector('#cartCount').textContent=cart.length;document.querySelector('#cartItems').innerHTML=cart.map((p,i)=>`<div class="cart-item"><div><b>${p.name}</b><br><small>${p.brand}</small></div><div>${money(p.price)} <button onclick="cart.splice(${i},1);updateCart()">×</button></div></div>`).join('')||'<p>Koszyk jest pusty.</p>';document.querySelector('#cartTotal').textContent=money(cart.reduce((s,p)=>s+p.price,0))}
function toggleCart(){document.querySelector('#cartPanel').classList.toggle('open');document.querySelector('#shade').classList.toggle('open')}
function details(id){let p=products.find(x=>x.id===id);if(p.box){document.querySelector('#boxArea').value=p.box;document.querySelector('#area').focus();document.querySelector('.calc-card').scrollIntoView({behavior:'smooth'});calculate()}else alert(`${p.brand} — ${p.name}\nEAN: ${p.ean}\nCena: ${money(p.price)}`)}
function calculate(){let area=+document.querySelector('#area').value,waste=+document.querySelector('#waste').value,box=+document.querySelector('#boxArea').value;if(area<=0||box<=0)return;let target=area*(1+waste/100),boxes=Math.ceil(target/box),real=boxes*box;document.querySelector('#calcResult').innerHTML=`Potrzeba <b>${boxes} paczek</b><br>Zakupisz: <b>${real.toFixed(2)} m²</b><br>Powierzchnia z zapasem: ${target.toFixed(2)} m²`}
render();calculate();updateCart();
